name: SamplePipeline
inputTopic:  raw_events
outputTopic: notifications
input:
   eventid: String
   user: String
   userid: String
   email: String
   srcIp: String
   createDate: String
   country: String
   city: String
   deviceType: String
   deviceName: String
   deviceAuth: String
   application: String
rule:
   - name: map
     weight: 10
     if-key:
       eq: "#any()"
     do-map: "#value(email)"
   - name: deny-filter
     weight: 20
     if-key:
       eq: "#string(ceo@abc.com)"
     do-deny:         
   - name: allow-filter
     weight: 30
     if-value-email:
       match: "#pattern(*@microsoft.com)"
     do-allow: 
   - name: allow-filter
     weight: 35
     if-value-srcip:
       match: "#pattern(^(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.){3}([01]?\\d\\d?|2[0-4]\\d|25[0-5])$)"
     do-allow: 
   - name: deny-filter
     weight: 40
     if-value-id:
        eq: "#string()"
     do-deny:
   - name: map
     weight: 50
     if-key:
       eq: "#any()"
     do-map: "#concat(#key(),#value(id))"
   - name: group
     weight: 60
     do-window: "#window(value-srcip, 5)"
  