name: SamplePipeline
inputTopic:  analytic_events
outputTopic: notifications
input:
   eventId: String
   user: String
   userId: String
   email: String
   srcIp: String
   createDate: String
   country: String
   city: String
   deviceType: String
   deviceName: String
   deviceAuth: String
   application: String
notify:
   - userId
   - email
rule:
   - name: map
     weight: 10
     if-key:
       eq: "#any()"
     do-map: "#value(email)"         
   - name: allow-filter
     weight: 35
     if-value-srcIp:
       match: "#pattern(^(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.){3}([01]?\\d\\d?|2[0-4]\\d|25[0-5])$)"
     do-allow: 
   - name: group
     weight: 60
     do-window: "#window(srcIp,5)"
  
